w3c/maturity-model

- index.html
also added links to the Github issues and email
> Added Introduction

- index.html
Incorporated all content from maturity model
> Move google doc to github

- index.html
Reverted the errored changes and left just the Appendix. I think
> Add appendix contributors

- README.md
James Nurthen's comment in #48 to add a link to the About made me think to also add a link in the repository readme.
> Add link to current draft in README

- index.html
This is a proposal to clarify the abstract (for consideration by the Maturity Model subgroup).
> Generalize and clarify the abstract to give a better understanding of the relationship of this document to other work.

- index.html
Tweaked editor's note in the [Assessment Template section](https://w3c.github.io/maturity-model/#assessment-template). 
- Changed "Google Sheets" to "Excel". 
- Change "is" to say "but is envisioned as HTML."
- Removed the link to the spreadsheet.
> Update per August 3 meeting minutes

- w3c.json
per https://w3c.github.io/w3c.json.html
> Mark repo as host of Note track work

- index.html
Added appendix and roles table/info for proof points and dimensions
> Adding roles table and appendix

- index.html
as discussed on 7/19/2023 call to help with HTML github process.
> added Charles as an editor and contributor

- index.html
This has the latest word changes suggested by Sheri.
> Editors note 2 4 1

- index.html
Also fixed H4 to H3 in the Procurement section.
> have section "Ratings for Evaluation" point back to the 2.4.1 section to download latest file

- index.html
Also removed dangling </p> tag.
> Updated List of Contributors to include those in our TF participants list

- index.html
Capitalization of Accessibility Policy
> Fixes #141

- index.html
as discussed in meeting 2/7/24
> fixes #104

- index.html
Added David's suggested changes to fix this issue.
> Fixes #101

- index.html
added new definition Linked to definition from content
> Fixes #143

- index.html
also fixed definition of ACR and referenced all in document with key term
> Fixes #216

- index.html
reversed columns Procurement and Personnel to match rest of document order of dimensions.
> Fixes #183

- index.html
Added Jeff's suggested text to each dimension's proof points.
Updated the spreadsheet to include this new proof point section.
Fixed a number of other issues with the spreadsheet including an accessibility issue.
> Dimension goals and metrics

- index.html
1. 2.4 paragraph changed
2. Evaluation points changed for dimensions
> Assessment and Evaluation changes

- index.html
Sync is complete please have a look
> Document and tool sync 

- index.html
> Edited abstract

- index.html
- **Moving Key Terms to it's own H2 above Acknowledgements**
- **textual edits to the Intro**
> Draft Edits to the Introduction

- index.html
Risk Acceptance Proof Point added to Oversight & Culture
> Risk Acceptance Proof Point

- index.html
Editor's not about documents being out of sync is no longer true, and it won't be true at the time of publication. So, I deleted it
> Deleted 1 Editors Note

- index.html
Added Financial Planning Proof Point to Oversight & Culture
Resolves Github Issue #244
> Financial Planning Proof Point

- index.html
> heading levels fixed

- index.html
> fixed #324
